Using Anaconda & Jupyter Notebook to perform the same.<br>
Numpy is python Library https://numpy.org/ which is writtern in c
- Helps with arrays and matrix
- Helps with numerical calculations.

Advantages: fixed size arrays, arrays elements have same data type.
            - Numpy array are ndimentional (ndarray)
            
- Elements of array are not known, its size is known/
- By default, the dtype of the created array is float64
- NumPy offers several functions to create arrays with initial placeholder content
- he function empty creates an array whose initial content is random. simillar for ones.

In [23]:
#importing Numpy Package
import numpy
#Assigning an Alias for Numpy to call
import numpy as np

#calling directly - i used this very rarely first two approach is preffered
from numpy import *

An Sample Exercise with Numpy

In [4]:
import numpy as np
a = np.arange(15)
#now this will give use evenly shaped array as below

([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)]

In [5]:
a= a.reshape(3,5)

(3, 5)

reshapping this gives us in a array format<br>
([0,1,2,3,4],<br>
 [5,6,7,8,9],<br>
 [10,11,12,13,14])

In [ ]:
a.shape

Simillar way can try these out
- ndarry.ndim: number of axes 
- ndarry.shape: tuple of array dimensions         --> **a.shape**
- ndarry.size: the total number of elements of the array    --> a.size 
- ndarray.dtype: type of elements in the array     -> rep 32 bit signed int 'int32'
- ndarray.itemsize: size in bytes of each array element
- ndarray.data: the buffer containing the actual elements 
of the array.

## what you will learn moving forward
- Intial Place Holder
- Arrange Function
- Linespace Function
- Arthematic Operations
- Unary Operations
- Slicing

# Creating an Array 

In [6]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
#you can see above we created an array a with list using array function
#checking the above array type
a.dtype

dtype('int32')

array function transforms sequences of sequences 
into two-dimensional arrays

In [8]:
b= np.array([(1.5,2,3),(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
#now checking the dimention of it
b.ndim

2

### Creating a 3Dimentional  Array

In [11]:
c= np.array([[[1,2], [3,4]],[[3,7],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[3, 7],
        [7, 8]]])

In [12]:
c.ndim

3

#### NumPy offers several functions to create arrays with initial placeholder content

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
#Array with initial Placeholder content
np.empty((2,2))

array([[9.34604358e-307, 3.44897822e-307],
       [3.33774490e-307, 2.55896905e-307]])

## Arrange function 

In [19]:
np.arange(10, 30, 5) # Return evenly spaced values 
# within a given interval (5).


array([10, 15, 20, 25])

In [20]:
np.arange(0, 2, 0.3) # Accepts float arguments.


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

### Line Space Function in Array

In [27]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [28]:
#arrange with floating points have some manual issue in predicting the numbers so using linespace for the same.

### Arthemitic operations 

In [30]:
a=np.array([20,30,40,50])
b= np.arange(4)               #note the arange spelling
b

array([0, 1, 2, 3])

In [32]:
c=a-b
c

array([20, 29, 38, 47])

In [33]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [34]:
a<50

array([ True,  True,  True, False])

In [35]:
a= np.array([[1,1], [0,1]])
b= np.array([[2,0], [3,4]])
a*b
#matrix multiplication can be used with @ "a@b" or use dot function

array([[2, 0],
       [0, 4]])

##### Usage of dot function or can use matmul function for the same

In [36]:
h = [[1, 2], [3, 4]]
i = [[5, 6], [7, 8]]
np.dot(h,i)

array([[19, 22],
       [43, 50]])